version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  ci:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: 'yarn'
      - add_ssh_keys
      - run: 'yarn run ci'

workflows:
  version: 2
  # On every commit
  commit:
    jobs:
      - ci
